# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
m_sq: 4
lam: 0
use_arxiv_version: false

# Model
base: standard_normal
model: real_nvp
model_spec:
    n_affine: 2

# Training length
n_batch: 1000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001
