# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
m_sq: 4
lam: 0
use_arxiv_version: false

# Base
base: standard_normal

# Model
n_affine: 2

# Networks
standardise_inputs: false
network_spec:
    s:
        hidden_shape: [24]
        activation: leaky_relu
        final_activation: leaky_relu
        do_batch_norm: false
    t:
        hidden_shape: [24]
        activation: leaky_relu
        final_activation: null
        do_batch_norm: false

# Training length
n_batch: 2000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001
