# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: o2
beta: 0.7

# Base
base: circular_uniform

# Model
model: projection
n_affine: 4

# Networks
standardise_inputs: true
s_network_spec:
    hidden_shape: [24]
    activation: leaky_relu
    final_activation: tanh
    do_batch_norm: false

t_network_spec:
    hidden_shape: [24]
    activation: leaky_relu
    final_activation: null
    do_batch_norm: false

# Training
n_batch: 1000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001

# Scheduler
verbose_scheduler: true
lr_reduction_factor: 0.5
