# Lattice
lattice_length: 6
lattice_dimension: 2

# Theory
theory: "phi_four"
m_sq: 4
lam: 0
use_arxiv_version: False

# Base distribution
base_dist: "normal"

# Flow model
flow_model: "real_nvp"
n_affine: 2
hidden_nodes: [24]
n_batch: 2000

# Training length
epochs: 3000
save_interval: 1000

# Optimizer ('adam', 'adadelta')
optimizer: 'adam'
optimizer_kwargs:
    lr: 0.01

# Scheduler
scheduler_kwargs:
    verbose: true
    factor: 0.5
    patience: 500
