# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: "phi_four"
m_sq: 4
lam: 0
use_arxiv_version: False

# Base
base: "standard_normal"

# Networks
hidden_nodes: [24]
n_affine: 4
n_batch: 1000

# Training length
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: 'adam'
lr: 0.01

# Scheduler
factor: 0.5
