# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: "phi_four"
m_sq: 4
lam: 0
use_arxiv_version: False

# Base
base: "standard_normal"

# Model
n_affine: 4

# Networks
standardise_inputs: true
network_spec:
    s:
        hidden_shape: [24]
        activation: "leaky_relu"
        final_activation: "leaky_relu"
        do_batch_norm: false
    t:
        hidden_shape: [24]
        activation: "leaky_relu"
        final_activation: "null"
        do_batch_norm: false


# Training
n_batch: 1000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: 'adam'
learning_rate: 0.001

# Scheduler
verbose_scheduler: true
lr_reduction_factor: 0.5
