# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: von_mises
concentration: 0.7
mean.0

# Model
base: circular_uniform
model: real_nvp_circle
model_spec:
    n_affine: 1
    hidden_shape: [24]
          
# Training
n_batch: 1000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001

# Scheduler
verbose_scheduler: true
lr_reduction_factor: 0.5
