# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: o3
beta: 3.5

# Model
base: spherical_uniform
model: real_nvp_sphere
model_spec:
    n_affine: 2
    hidden_shape: [36]
n_mixture: 1  # doesn't seem to work well with convex combinations
          
# Training
n_batch: 1000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001

# Scheduler
verbose_scheduler: true
lr_reduction_factor: 0.5
