# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
m_sq: -4
lam: 1.0
use_arxiv_version: false

# Model
base: normal
sigma: 0.9
model: real_nvp
model_spec:
    n_affine: 6
    hidden_shape: [72]
    activation: tanh
    s_final_activation: null
    symmetric: true

# Training
n_batch: 1000
epochs: 10000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001

# Scheduler
verbose_scheduler: true
lr_reduction_factor: 0.5

