# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
m_sq: -4
lam: 5.0
use_arxiv_version: false

# Model
base: standard_normal
model: real_nvp
model_spec:
    n_affine: 4
    hidden_shape: [36]
n_mixture: 1

# Training
n_batch: 1000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001

# Scheduler
verbose_scheduler: true
lr_reduction_factor: 0.5

