# Lattice
lattice_length: 6
lattice_dimension: 2

# Action
theory: "spin"
theory_N: 3
beta: 0.05

# Base distrbution
base_dist: "uniform"

# Networks
flow_model: "real_nvp"
hidden_nodes: [36]
n_affine: 4
n_batch: 3000

# Training length
epochs: 3000
save_interval: 1000

# Optimizer ('adam', 'adadelta')
optimizer: 'adam'
optimizer_kwargs:
    lr: 0.01

# Scheduler
scheduler_kwargs:
    verbose: true
    factor: 0.5
    patience: 500
