training_output: test_model

cp_id: -1
target_length: 10000

thermalisation: 100
sample_interval: null
n_boot: 1000

meta:
  author: New User
  title: Training Report
  keywords: [example]

template: report.md

actions_:
  - report(main=True)
