# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
parameterisation: nicoli2020
couplings:
    kappa: 0.3
    lam: 0.022

# Model
base: normal
sigma: 0.5
model: rational_quadratic_spline
model_spec:
    hidden_shape: [72]
    activation: tanh
    interval: 4
    n_segments: 8
    

# Training
n_batch: 2000
epochs: 10000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.001

# Scheduler
verbose_scheduler: true
lr_reduction_factor: 0.5
min_learning_rate: 0.0000001

