# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
parameterisation: albergo2019
couplings:
    m_sq: -4
    lam: 6.975

# Model
base: normal
sigma: 0.5
model: spline_sandwich
model_spec:
    hidden_shape: [36,36]
    activation: tanh
    
    n_affine: 1
    symmetric_networks: true
    bnorm: false
    s_final_activation: null

    n_pairs: 1
    symmetric_spline: false
    n_segments: 8
    interval: 1.2


# Training
n_batch: 1000
epochs: 12000
save_interval: 1000

# Optimizer
optimizer: adamw
learning_rate: 0.001

# Scheduler
scheduler: warm
T_0: 4000
T_mult: 2
increase_batch: [9000, 1000]
decrease_lr: false

